### ISSUE TITLE
It is not clear how to embed the resources

### ISSUE THREAD

**Issue by akamensky** [therecipe/qt#162]
In QT Creator projects it is simple to embed resources into application using `.qrc` file. However there is no example nor any clear way to do so with these bindings and using qtdeploy.

For example creating QIcon from string works only if I use absolute path to the icon file.  Attempting to create .qrc file with prefix and path to icon does no effect.

**Comment by akamensky** [comment]
Looking at closed issue #47 it seems the files will be generated on the fly from `.ui` files, however in my project (Which I am porting from C++ to Go) there is no `.ui` file and `.qrc` is included in `.pro` with `RESOURCES = resources.qrc`, which ideally I would also want to keep same way...

**Comment by therecipe** [comment]
Hey

Yes, currently the resource bundling is limited to the "magical" `qml` folder.
You place everything there (qml files, images, ui files, ...) and `rcc` is invoked by either `qtrcc` or `qtdeploy` to create the `*.qrc` and later `*.cpp` file.

But your are right,  being able to use custom `*.qrc` files could be really useful.
For example [here](https://github.com/therecipe/qt/tree/master/internal/examples/qml/drawer_nav_x) I had to place everything in the qml folder and therefore change some paths inside the qml files.
That unnecessary complicated porting the example from C++ to Go.

So I made some changes to `qtrcc`, to use all `*.qrc` files in the root of your project folder.
I will push the changes tomorrow, because I encountered a problem in `qtdeploy` today that needs to be fixed first for this to work.

**Comment by akamensky** [comment]
I will check this qml folder. Thanks. 

One question though - this means that the resources will be bundled on qtdeploy only? In case when I need to debug the application (I am using IntelliJ IDEA) those won't be loaded then? Or is there a way to load them?

**Comment by akamensky** [comment]
I am still not clear how would I access those resources placed in `qml` directory. I can see `.cpp` and `.qrc` files being generated and containing byte representation of the images, but I cannot use them from the go code. My code does not use QML at all. It is based on QWidgets.

So I tried using `gui.NewQIcon5(fileName string)` to n/a, I tried a few other approach with same outcome. I presume that is due to my lack of understanding how this should work. So maybe some code snippet would be helpful...

**Comment by therecipe** [comment]
> One question though - this means that the resources will be bundled on qtdeploy only? In case when I need to debug the application (I am using IntelliJ IDEA) those won't be loaded then? Or is there a way to load them?

You can generate the needed `*.qrc`, `*.go` and `*.cpp` files by using `qtrcc` in your project folder.
Or by using `qtrcc path/to/your/project`


Here is an example that should work.
You just need to create a `qml` folder that contains a valid `icon.png`

```
.
├── main.go
└── qml
    └── icon.png
```


```go
package main

import (
	"os"

	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	widgets.NewQPushButton3(gui.NewQIcon5(":/qml/icon.png"), "hello", nil).Show()

	//if a QUrl should point to an embedded resource you need to prefix the path with `qrc:/`
	//core.NewQUrl3("qrc:/qml/icon.png", 0)

	widgets.QApplication_Exec()
}
```

**Comment by therecipe** [comment]
With https://github.com/therecipe/qt/commit/e201af8a0fed43d8a1edddc912ebe777eb7bc052 `qtrcc` should detect *.qrc files in the root folder of your project and embed the resources.

Here is an example that should work now: https://github.com/therecipe/qt/tree/master/internal/examples/qml/drawer_nav_x

**Comment by akamensky** [comment]
Yup, that works well with manually calling `qtrcc`, the only annoyance is that resources must be placed inside main module sources directory. Annoying voices in my head are telling me that this is not the best solution. Right now I end up with following structure:

```
$(GOPATH)
|
+-- src/
       +-- main/
       |       +-- images/
       |       |         +-- image.png
       |       +-- main.go
       |       +-- resources.qrc
       +-- github.com/...
       +-- golang.org/...
       +-- (other modules)
```

I don't think hiding `.qrc` and embeddable resources inside is such a good idea, I think ideally structure should be more like:

```
$(GOPATH)
|
+-- resources.qrc
+-- images/
|         +-- image.png
+-- src/
       +-- main/
       |       +-- main.go
       +-- github.com/...
       +-- golang.org/...
       +-- (other modules)
```

I think the argument like `--output-dir=/path/to/dir` is in order for `qtrcc` so that developer could call it with `./bin/qtrcc --output-dir=./src/main/` which would write the output files to appropriate location without the need to keep all resources in there...

**Comment by therecipe** [comment]
> I think the argument like --output-dir=/path/to/dir is in order for qtrcc so that developer could call it with ./bin/qtrcc --output-dir=./src/main/ which would write the output files to appropriate location without the need to keep all resources in there...

Yes, I like the idea.
I will look into it.

**Comment by therecipe** [comment]
And I added this flag with 8e6d46d as well.

You can now define an alternative output dir (for the *.go and *.cpp files) with `qtrcc -o=...`

**Comment by akamensky** [comment]
Confirmed, it works with this argument almost as expected. However I still see that `rrc.qrc` and `qml/` are still created in `$CWD` instead of the one specified with `-o=...`, though in case of detecting existing `.qrc` file and non-existent `qml/` directory not sure why would need to create them at all :) Not a big issue though.

Can close I guess.

**Comment by akamensky** [comment]
Actually just tried also `qtdeploy`, it will execute qtrcc without those options. Which then results in missing resources in application.

Should there be a flag for `qtdeploy` as well? As common would be then something like `--qtrcc-flags="..."` where `...` can be string (including spaces) that will be passed as arguments to qtrcc?

**Comment by therecipe** [comment]
> However I still see that rrc.qrc and qml/ are still created in $CWD instead of the one specified with ...

Yes, it's either $CWD or the first argument after the flags.
This should usually be the place were the other *.qrc files are located as well. I thought spreading those *.qrc files wouldn't be a good idea. And so only the really needed *.cpp and *.go files are placed inside the output-dir. What do you think?

> though in case of detecting existing .qrc file and non-existent qml/ directory not sure why would need to create them at all :)

Yes, I will change that so that the qml dir won't be created if there are *.qrc files already.

> Should there be a flag for qtdeploy as well? As common would be then something like --qtrcc-flags="..." where ... can be string (including spaces) that will be passed as arguments to qtrrc?

The standard env flags, `qt_dir` and such flags as `qt_version` (not yet available) should be passed to `qtdeploy` directly, but those specific qtrcc flags `-o` should probably be passed as you suggested.

I hadn't thought about such use cases before. Now the idea of a config file starts to get appealing (as the lesser evil), if there is no way to use environment variables. So I will think about it.

> Found a slightly bigger issue with this. To actually embed resources it is required to have empty rrc.qrc and qml/ in project directory.

I will look into it.

**Comment by akamensky** [comment]
I think can use either CLI arguments, env vars or config file. Any is good as long as there will be clear documentation on that. If you say which way would be implemented I could send PR for README (afraid not for code yet as pretty busy on current project).

**Comment by therecipe** [comment]
> I think can use either CLI arguments, env vars or config file. Any is good as long as there will be clear documentation on that. If you say which way would be implemented I could send PR for README (afraid not for code yet as pretty busy on current project).

Okay :)

> Actually I would prefer having config file, but there is one problem with it. It does not recognize standard env vars, nor does path expansion (so that I currently cannot use QT_DIR that starts with neither $HOME nor ~)

Yes, that could be a problem, but there is probably some simple workaround to handle this.

> Thank you for explanation.

You are welcome :)

**Comment by akamensky** [comment]
@therecipe Since I need this to work for `qtdeploy` I've sent a PR #182, as I can see from code `qtdeploy` does not call the `qtrcc` binary. Instead it uses internal code.

Thus I've implemented environment variables.

For consistent results I would suggest to change the logic and instead of direct code execution from `qtdeploy` to just `qtrcc`, this will simplify a lot I believe and allow `single point` of changes.

**Comment by therecipe** [comment]
Thanks for the PR :)

>For consistent results I would suggest to change the logic and instead of direct code execution from qtdeploy to just execute pre-built qtrcc, this will simplify a lot I believe and allow single point of changes.

Just 4 days ago I made the change to use the internal code instead of the binaries https://github.com/therecipe/qt/commit/7f3481d85f4349dfa06beb76efe1e51f101f788b :D
But prior to that I had it exactly for the reason you suggested, to get a single point of change/failure.

The change was mainly done to share the `internal/parser.State` with the other tools, to speed-up deploying with `qtdeploy` (and the tests in `qtsetup`). And also somewhat to unify the flag usage among the tools. And I think to solve the logrus log escaping issues.

The plan is/was to just parse additional tool specific flags (`-o` in `qtrcc` for example) in `qt/cmd/...` and then directly call the "main" tool function in `qt/internal/cmd/...`, with the flag values passed as arguments to the "main" tool function.  This way there is just some minor inconsistency, which is limited to different arguments being passed to the "main" tool function.

**Comment by akamensky** [comment]
> Thanks for the PR :)

Thanks for merging it ;) now I can build the final bundle easily.

> Just 4 days ago I made the change to use the internal code instead of the binaries

I still believe it is so much better to call binaries than sharing the code. This would help to handle this like this one and there are great examples of tools that do exactly this way (like GCC for example or Clang).

I think it would be better to revert to previous implementation, then I could help to implement needed CLI arguments and environment variables handling with correct priorities etc. I could also look at implementing them in a more unified way (with ability to use other env var and shell expansions etc).

**Comment by therecipe** [comment]
>I still believe it is so much better to call binaries than sharing the code.

Usually yes, and it's still possible for `qtrcc`, but `qtmoc` and `qtminimal` (if used from `qtdeploy`) share a state now to save 5 sec which is otherwise wasted with parsing the *.index files and preparing the state. This can be also useful to implement something like this later:
`qtdeploy build desktop -android -ios -sailfish` to speed-up the deployment of additional targets.

>I think it would be better to revert to previous implementation, then I could help to implement needed CLI arguments and environment variables handling with correct priorities etc. I could also look at implementing them in a more unified way (with ability to use other env var and shell expansions etc).

What about if I let the `qt/cmd/...` tools just call one function? So something like this for `qtrcc` for example:
```go
package main
import "github.com/therecipe/qt/internal/cmd/rcc"
func main() { rcc.Rcc(false) } //rcc.Rcc maybe with a bool parameter to indicate if called from qtdeploy
```

Then there is just one single entry point, and all the code could stay inside `internal/cmd/rcc` and I could still make use of the shared state.
And inside `rcc.Rcc` you could parse additionally flags if called from `qtdeploy` for example.

Something like this:
```go
package rcc

func Rcc(isCalledFromDeploy bool){

if isCalledFromDeploy{
var rccflags = flag.String("qtrcc-flags", ...)

//and then the additional flags just need to be parsed again
}

}
```

**Comment by TommyO** [comment]
I also had a problem with the rigid qml directory structure, even went so far as to fork and try to solve it myself (now woefully out of date ;) ), so I'm glad to see these changes!

I do still need to use different `.qml` files and other resources based on a specific platform build. Currently I have a `desktop.qrc`, `mobile.qrc` and `common.qrc`, and include the ones I need at compile time. What would be the best way to do this? My thoughts when I was forking was to accept a list of `.qrc` file names as a parameter rather than to look for all in a specific place. Might also solve akamensky's issue with having a required location. Maybe an `-i` flag that can be repeated for each file/glob pattern?

Always willing to do the labor if you want to point me in a specific direction.

PS. Qt itself supports `+linux/somefile.img` , `+ios/somefile.img` etc. by using [QFileSelector](http://doc.qt.io/qt-5/qfileselector.html) which I'm assuming still works here (although not tested, yet) but that only gets me so far. I need to add some in addition to the built in ones. Could add them as Go flags possibly, so I'm open to other ways to solve my problem, but it may not solve other people's use cases.

**Comment by therecipe** [comment]
Hey

Yes, the resource bundling is not really customizable yet.

> My thoughts when I was forking was to accept a list of .qrc file names as a parameter rather than to look for all in a specific place. Might also solve akamensky's issue with having a required location. Maybe an -i flag that can be repeated for each file/glob pattern?

Yes, that should work, and it could be implemented with a "qtrcc" flag for qtdeploy:
`qtdeploy --qtrcc-flags="-i path/to/*.qrc"`
But then qtdeploy needs to call the `qtrcc` binary again, instead of using the internal function.
This would make qtdeploy a bit slower, but that's okay. (The change needs to happen sooner or later anyway)

Or do you use qtrcc/qtmoc/qtminimal and `go build -tags=minimal ...` directly instead of qtdeploy? 
Then the changes, could be made to "qtrcc" only.

>Always willing to do the labor if you want to point me in a specific direction.

Feel free to poke around and send a PR, but be warned :D the code is a bit messy and undocumented.
I'm currently making some changes to the code generator, and will then start to cleanup again.

> I need to add some in addition to the built in ones. Could add them as Go flags possibly, so I'm open to other ways to solve my problem, but it may not solve other people's use cases.

How about build tags similar to how Go uses them? `// +build android` in *.go files.
There just need to be made some changes to `qtrcc` to detect comments like this
`<!-- +build android -->` at the top of the *.qrc files. To let `qtrcc` know, which file to include.
