### ISSUE TITLE
drag & drop

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#39]
Hi,

Trying drag and drop with QListWidget. When I attempt to drop the cursor shows circle and slash as if it can't accept drops. Also on the MimeData there doesn't seem to be a Urls() method.

Thanks 

```go
	gp.ValueList = Valuelist{widgets.NewQListWidget(nil)}

	gp.ValueList.SetAcceptDrops(true)

	vlayout.AddWidget(gp.ValueList, 0, 0)

	gp.ValueList.ConnectDragEnterEvent(gp.ValueList.DragEnterEvent)
	gp.ValueList.ConnectDropEvent(gp.ValueList.DropEvent)
```

```go
	import (
		"github.com/therecipe/qt/core"
		"github.com/therecipe/qt/gui"
		"github.com/therecipe/qt/widgets"
	)

	type Valuelist struct{ *widgets.QListWidget }

	func (v *Valuelist) DragEnterEvent(e *gui.QDragEnterEvent) {
		e.AcceptProposedAction()
		//	if e.MimeData().HasUrls() {
		//		e.AcceptProposedAction()
		//	}
	}

	func (v *Valuelist) DropEvent(e *gui.QDropEvent) {
		//	if e.MimeData().HasUrls() {
		e.SetDropAction(core.Qt__CopyAction)
		e.AcceptProposedAction()
		e.SetAccepted(true)

		for _, i := range e.MimeData().Formats() { // Urls() ??
			v.AddItem(i)
		}
		//	}
	}
```

**Comment by therecipe** [comment]
Hey

Currently generic list are not supported https://github.com/therecipe/qt/issues/9, but I'm planning to add them.

I will also take a look at this drag and drop example.
(It seems like the `dragEnterEvent` is called, but not the `dropEvent` ?)

**Comment by therecipe** [comment]
It seems like you need to connect the `DragMoveEvent`, otherwise it won't work.

```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

type Valuelist struct{ *widgets.QListWidget }

func main() {

	widgets.NewQApplication(len(os.Args), os.Args)

	var window = widgets.NewQMainWindow(nil, 0)

	var vlayout = widgets.NewQVBoxLayout()
	window.Layout().DestroyQObject()
	window.SetLayout(vlayout)

	var gp = struct{ ValueList Valuelist }{}

	gp.ValueList = Valuelist{widgets.NewQListWidget(nil)}

	gp.ValueList.SetAcceptDrops(true)

	vlayout.AddWidget(gp.ValueList, 0, 0)

	gp.ValueList.ConnectDragEnterEvent(gp.ValueList.DragEnterEvent)
	gp.ValueList.ConnectDragMoveEvent(gp.ValueList.DragMoveEvent)
	gp.ValueList.ConnectDropEvent(gp.ValueList.DropEvent)

	window.Show()

	widgets.QApplication_Exec()
}

func (v *Valuelist) DragEnterEvent(e *gui.QDragEnterEvent) {
	e.AcceptProposedAction()
	//  if e.MimeData().HasUrls() {
	//      e.AcceptProposedAction()
	//  }
}

func (v *Valuelist) DragMoveEvent(e *gui.QDragMoveEvent) {
	e.AcceptProposedAction()
}

func (v *Valuelist) DropEvent(e *gui.QDropEvent) {
	//  if e.MimeData().HasUrls() {
	e.SetDropAction(core.Qt__CopyAction)
	e.AcceptProposedAction()
	e.SetAccepted(true)

	for _, i := range e.MimeData().Formats() { // Urls() ??
		v.AddItem(i)
	}
	//  }
}
```

**Comment by 5k3105** [comment]
C:\goworksp\src\local\qt_dnd                                                                                   
	λ qtdeploy                                                                                                     
																												   
																												   
	build_1                                                                                                        
	output:# local/qt_dnd                                                                                          
	C:\windows\go-build647165594\local\qt_dnd\_obj\_cgo_main.c: In function 'crosscall2':                          
	C:\windows\go-build647165594\local\qt_dnd\_obj\_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-param
	eter]                                                                                                          
	 void crosscall2(void(*fn)(void*, int), void *a, int c) { }                                                    
						   ^                                                                                       
	C:\windows\go-build647165594\local\qt_dnd\_obj\_cgo_main.c:2:46: warning: unused parameter 'a' [-Wunused-parame
	ter]                                                                                                           
	 void crosscall2(void(*fn)(void*, int), void *a, int c) { }                                                    
												  ^                                                                
	C:\windows\go-build647165594\local\qt_dnd\_obj\_cgo_main.c:2:53: warning: unused parameter 'c' [-Wunused-parame
	ter]                                                                                                           
	 void crosscall2(void(*fn)(void*, int), void *a, int c) { }                                                    
														 ^                                                         
	C:\windows\go-build647165594\local\qt_dnd\_obj\_cgo_main.c: In function '_cgo_allocate':                       
	C:\windows\go-build647165594\local\qt_dnd\_obj\_cgo_main.c:5:26: warning: unused parameter 'a' [-Wunused-parame
	ter]                                                                                                           
	 void _cgo_allocate(void *a, int c) { }                                                                        
							  ^                                                                                    
	C:\windows\go-build647165594\local\qt_dnd\_obj\_cgo_main.c:5:33: warning: unused parameter 'c' [-Wunused-parame
	ter]                                                                                                           
	 void _cgo_allocate(void *a, int c) { }                                                                        
									 ^                                                                             
	C:\windows\go-build647165594\local\qt_dnd\_obj\_cgo_main.c: In function '_cgo_panic':                          
	C:\windows\go-build647165594\local\qt_dnd\_obj\_cgo_main.c:6:23: warning: unused parameter 'a' [-Wunused-parame
	ter]                                                                                                           
	 void _cgo_panic(void *a, int c) { }                                                                           
						   ^                                                                                       
	C:\windows\go-build647165594\local\qt_dnd\_obj\_cgo_main.c:6:30: warning: unused parameter 'c' [-Wunused-parame
	ter]                                                                                                           
	 void _cgo_panic(void *a, int c) { }                                                                           
								  ^                                                                                
	# local/qt_dnd                                                                                                 
	.\moc.go:146: (*Valuelist).DropEvent redeclared in this block                                                  
			previous declaration at .\main.go:51                                                                   
	.\moc.go:146: method redeclared: Valuelist.DropEvent                                                           
			method(*Valuelist) func(*gui.QDropEvent)                                                               
			method(*Valuelist) func(gui.QDropEvent_ITF)                                                            
	.\moc.go:467: (*Valuelist).DragMoveEvent redeclared in this block                                              
			previous declaration at .\main.go:47                                                                   
	.\moc.go:467: method redeclared: Valuelist.DragMoveEvent                                                       
			method(*Valuelist) func(*gui.QDragMoveEvent)                                                           
			method(*Valuelist) func(gui.QDragMoveEvent_ITF)                                                        
	.\moc.go:1668: (*Valuelist).DragEnterEvent redeclared in this block                                            
			previous declaration at .\main.go:40                                                                   
	.\moc.go:1668: method redeclared: Valuelist.DragEnterEvent                                                     
			method(*Valuelist) func(*gui.QDragEnterEvent)                                                          
			method(*Valuelist) func(gui.QDragEnterEvent_ITF)                                                       
																												   
	error:exit status 2

**Comment by therecipe** [comment]
Sorry, my fault.

I just suffixed the function names with `_Implementation` and it works now.
It's probably better to never try to redeclare / override / overshadow the functions names (since it will only work on signals anyway).

```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

type Valuelist struct{ *widgets.QListWidget }

func main() {

	widgets.NewQApplication(len(os.Args), os.Args)

	var window = widgets.NewQMainWindow(nil, 0)

	var vlayout = widgets.NewQVBoxLayout()
	window.Layout().DestroyQObject()
	window.SetLayout(vlayout)

	var gp = struct{ ValueList Valuelist }{}

	gp.ValueList = Valuelist{widgets.NewQListWidget(nil)}

	gp.ValueList.SetAcceptDrops(true)

	vlayout.AddWidget(gp.ValueList, 0, 0)

	gp.ValueList.ConnectDragEnterEvent(gp.ValueList.DragEnterEvent_Implementation)
	gp.ValueList.ConnectDragMoveEvent(gp.ValueList.DragMoveEvent_Implementation)
	gp.ValueList.ConnectDropEvent(gp.ValueList.DropEvent_Implementation)

	window.Show()

	widgets.QApplication_Exec()
}

func (v *Valuelist) DragEnterEvent_Implementation(e *gui.QDragEnterEvent) {
	e.AcceptProposedAction()
	//  if e.MimeData().HasUrls() {
	//      e.AcceptProposedAction()
	//  }
}

func (v *Valuelist) DragMoveEvent_Implementation(e *gui.QDragMoveEvent) {
	e.AcceptProposedAction()
}

func (v *Valuelist) DropEvent_Implementation(e *gui.QDropEvent) {
	//  if e.MimeData().HasUrls() {
	e.SetDropAction(core.Qt__CopyAction)
	e.AcceptProposedAction()
	e.SetAccepted(true)

	for _, i := range e.MimeData().Formats() { // Urls() ??
		v.AddItem(i)
	}
	//  }
}
```

**Comment by 5k3105** [comment]
Hi.

Thank you. It's working. Using

```go
	for _, i := range strings.Split(e.MimeData().Text(), "\n") { // Urls() ??
		if i != "" {
			v.AddItem(i)
		}
```

to get file paths.

**Comment by sndnvaps** [comment]
hi @therecipe 
get some problem with build dropsite.go in example ,
i have do some change, but still not work
```go
//source: http://doc.qt.io/qt-5/qtwidgets-draganddrop-dropsite-example.html

package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

type DropSiteWindow struct {
	widgets.QWidget

	_ func(mimeData *core.QMimeData) `slot:"updateFormatsTable"`
}

func (d *DropSiteWindow) UpdateFormatsTable(mimeData *core.QMimeData) {

}

func (d *DropSiteWindow) ConnectUpdateFormatsTable(func(mimeData *core.QMimeData)) {

}

func NewDropSiteWindow(i interface{}, d int) DropSiteWindow {

	var dsw DropSiteWindow
	return dsw
}

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	var window = NewDropSiteWindow(nil, 0)

	var abstractLabel = widgets.NewQLabel2("This example accepts drags from other applications and displays the MIME types provided by the drag object.", nil, 0)
	abstractLabel.SetWordWrap(true)
	abstractLabel.AdjustSize()

	var dropArea = initDropArea()
	dropArea.ConnectChanged(func(mimeData *core.QMimeData) { window.UpdateFormatsTable(mimeData) })

	var formatsTable = widgets.NewQTableWidget(nil)
	formatsTable.SetColumnCount(2)
	formatsTable.SetEditTriggers(widgets.QAbstractItemView__NoEditTriggers)
	formatsTable.SetHorizontalHeaderLabels([]string{"Format", "Content"})
	formatsTable.HorizontalHeader().SetStretchLastSection(true)

	window.ConnectUpdateFormatsTable(func(mimeData *core.QMimeData) {
		formatsTable.SetRowCount(0)

		if mimeData == nil {
			return
		}

		for _, format := range mimeData.Formats() {
			var formatItem = widgets.NewQTableWidgetItem2(format, 0)
			formatItem.SetFlags(core.Qt__ItemIsEnabled)
			formatItem.SetTextAlignment(int(core.Qt__AlignTop | core.Qt__AlignLeft))

			var text string

			switch format {
			case "text/plain":
				{
					text = mimeData.Text()
				}

			case "text/html":
				{
					text = mimeData.Html()
				}

			case "text/uri-list":
				{
					var urlList = mimeData.Urls()
					for i := 0; i < len(urlList) && i < 32; i++ {
						text += urlList[i].ToString(0) + " "
					}
				}

			default:
				{
					var data = []byte(mimeData.Data(format).ConstData())
					text = fmt.Sprintf("len %v: %v", len(data), data)
				}
			}

			var row = formatsTable.RowCount()
			formatsTable.InsertRow(row)
			formatsTable.SetItem(row, 0, widgets.NewQTableWidgetItem2(format, 0))
			formatsTable.SetItem(row, 1, widgets.NewQTableWidgetItem2(text, 0))
		}

		formatsTable.ResizeColumnToContents(0)
	})

	var (
		clearButton = widgets.NewQPushButton2("Clear", nil)
		quitButton  = widgets.NewQPushButton2("Quit", nil)

		buttonBox = widgets.NewQDialogButtonBox(nil)
	)

	buttonBox.AddButton(clearButton, widgets.QDialogButtonBox__ActionRole)
	buttonBox.AddButton(quitButton, widgets.QDialogButtonBox__RejectRole)

	quitButton.ConnectPressed(func() { window.Close() })
	clearButton.ConnectPressed(func() {
		dropArea.Clear()
		formatsTable.ClearContents()
		formatsTable.SetRowCount(0)
	})

	var mainLayout = widgets.NewQVBoxLayout()
	mainLayout.AddWidget(abstractLabel, 0, 0)
	mainLayout.AddWidget(dropArea, 0, 0)
	mainLayout.AddWidget(formatsTable, 0, 0)
	mainLayout.AddWidget(buttonBox, 0, 0)

	window.SetLayout(mainLayout)

	window.SetWindowTitle("Drop Site")
	window.SetMinimumSize2(350, 500)

	window.Show()

	widgets.QApplication_Exec()
}

type DropArea struct {
	widgets.QLabel

	_ func(mimeData *core.QMimeData) `signal:"changed"`
}

func (da *DropArea) Changed(mimeData *core.QMimeData) {

}

func (da *DropArea) ConnectChanged(func(mimeData *core.QMimeData)) {

}
func NewDropArea(i interface{}, num int) DropArea {
	var nda DropArea
	return nda
}

func initDropArea() *DropArea {
	var dropArea = NewDropArea(nil, 0)

	dropArea.SetMinimumSize2(200, 200)
	dropArea.SetFrameStyle(int(widgets.QFrame__Sunken) | int(widgets.QFrame__StyledPanel))
	dropArea.SetAlignment(core.Qt__AlignCenter)
	dropArea.SetAcceptDrops(true)
	dropArea.SetAutoFillBackground(true)
	dropArea.Clear()

	dropArea.ConnectDragEnterEvent(func(e *gui.QDragEnterEvent) {
		dropArea.SetText("<drop content>")
		dropArea.SetBackgroundRole(gui.QPalette__Highlight)

		e.AcceptProposedAction()
		dropArea.Changed(e.MimeData())
	})

	dropArea.ConnectDragMoveEvent(func(e *gui.QDragMoveEvent) {
		e.AcceptProposedAction()
	})

	dropArea.ConnectDropEvent(func(e *gui.QDropEvent) {
		var mimeData = e.MimeData()

		switch {
		case mimeData.HasImage():
			{
				dropArea.SetPixmap(gui.QPixmap_FromImage(gui.NewQImageFromPointer(mimeData.ImageData().ToImage()), 0))
			}

		case mimeData.HasHtml():
			{
				dropArea.SetText(mimeData.Html())
				dropArea.SetTextFormat(core.Qt__RichText)
			}

		case mimeData.HasUrls():
			{
				var (
					urlList = mimeData.Urls()
					text    string
				)
				for i := 0; i < len(urlList) && i < 32; i++ {
					text += urlList[i].Path(0) + "\n"
				}
				dropArea.SetText(text)
			}

		case mimeData.HasText():
			{
				dropArea.SetText(mimeData.Text())
				dropArea.SetTextFormat(core.Qt__PlainText)
			}

		default:
			{
				dropArea.SetText("can't display data")
			}
		}

		dropArea.SetBackgroundRole(gui.QPalette__Dark)
		e.AcceptProposedAction()
	})

	dropArea.ConnectDragLeaveEvent(func(e *gui.QDragLeaveEvent) {
		dropArea.Clear()
		e.Accept()
	})

	dropArea.ConnectClear(func() {
		dropArea.SetText("<drop content>")
		dropArea.SetBackgroundRole(gui.QPalette__Dark)

		dropArea.Changed(nil)
	})

	return &dropArea
}
```

go build get some problem:

```bash
C:\Users\Administrator\Source\Repos\gowork\src\github.com\therecipe\qt\internal\examples\widgets\dropsite>Finished running tool: D:\go\bin\go.exe build -i -o C:\Users\ADMINI~1\AppData\Local\Temp\go-code-check github.com\therecipe\qt\internal\examples\widgets\dropsite
C:\Users\Administrator\Source\Repos\gowork\src\github.com\therecipe\qt\internal\examples\widgets\dropsite\dropsite.go:59: mimeData.Formats undefined (type *core.QMimeData has no field or method Formats)
```

**Comment by spieglt** [comment]
I have had the `type *core.QMimeData has no field or method Formats` problem as well, on both Windows and Mac.

**Comment by therecipe** [comment]
@sndnvaps @spieglt
The function should be available again with https://github.com/therecipe/qt/commit/a4b55d8d3cec4f503a511db2a3ebb74b00bbc28b#diff-9bbdf1b6f8e66f0a346330f3be71a4d3
I tested the dropsite example on macOS, and it seems to work.

**Comment by spieglt** [comment]
Still getting the same error on Windows after pulling latest. Should I need to run `qtsetup` again or something?

**Comment by therecipe** [comment]
Sorry, yeah if you use the plain "go build" or "go run" commands then yes you will need to run the full setup again. If you on the other side just use `qtdeploy`, then re-building the tooling from `qt/cmd/...` should have been enough to make it work.

Also, btw if did use the "Fast Track" version on windows (i.e. the version without the need to manually install Qt) please update to https://github.com/therecipe/qt/commit/2bbbf34c6bd2db9d10bf1bcf2f38bbfb5912cf7f
I just fixed some issue where using `go run` or `go build` would result in a second installation of the binding, because the old cached versions couldn't be re-used.
If you use the "Official version" on window, then you can skip this.

**Comment by spieglt** [comment]
Thanks for following up so quickly. I have manually installed Qt (5.12.0) and only use `qtdeploy` but still get the error unfortunately.

**Comment by spieglt** [comment]
By the way, how does one use the "Fast Track" version? I've just been running the Qt installer, then `go get`ting this repo, then running `qtsetup`.

**Comment by therecipe** [comment]
>Thanks for following up so quickly. I have manually installed Qt (5.12.0) and only use qtdeploy but still get the error unfortunately.

No problem, maybe try to run
```
$(go env GOPATH)/bin/qtsetup -debug upgrade
```
or 
```
go get -u -v github.com/therecipe/qt/cmd/... && go clean -cache && go install -v github.com/therecipe/qt/cmd/...
```

If this is not working, then maybe try to remove the repo from your GOPATH and run the command from above once again

>By the way, how does one use the "Fast Track" version? I've just been running the Qt installer, then go getting this repo, then running qtsetup.

You basically only need to run
```
go get -u -v github.com/therecipe/qt/cmd/... && $(go env GOPATH)/bin/qtsetup
```
and the only prerequisites for this to work on a clean pc are to have Go, Git and an C++ compiler installed (on windows you won't even need an C++ compiler, as one will be automatically downloaded as well)

After you are done with this, check the `src/github.com/therecipe` dir, there should be a second folder created called `env_$(GOOS)_amd64_512` which should contains all the necessary Qt binaries for this to work

Also if you already have a "normal" Qt installation somewhere installed, then maybe rename or remove it (or change QT_DIR to point to `$(go env GOPATH)/src/github.com/therecipe/env_$(GOOS)_amd64_512`) before running the setup.

(You will know everything is setup correctly for the "Fast track" version, if `qtsetup check` gives you a QT_DIR that points to `$(go env GOPATH)/src/github.com/therecipe/env_$(GOOS)_amd64_512`)

**Comment by spieglt** [comment]
Thanks, that second command straightened it out.
