### ISSUE TITLE
"morestack on g0" error on IOS

### ISSUE THREAD

**Issue by vahid-sohrabloo** [therecipe/qt#451]
Sometimes I have "fatal: morestack on g0" error only in IOS. 
I don't have this error on Linux android and mac.
I use qml and bind signals to go. 
Whats mean this error and how to fix it?

**Comment by therecipe** [comment]
Hey

You probably have an infinite (or at least some deep) recursion somewhere: https://github.com/therecipe/qt/issues/399

Does your app crash right at the start, or only after some time went by?

**Comment by vahid-sohrabloo** [comment]
@therecipe  thanks for response
App started and then load and show a List view successfully but when I open another widget like drawer, app crash and give me that error

**Comment by therecipe** [comment]
Do you test your app on the simulator or on a real device?
Also which Go and Qt version did you use?

**Comment by vahid-sohrabloo** [comment]
I tested in simulator
Go 1.9
Qt 5.9.1

**Comment by vahid-sohrabloo** [comment]
I still have this error.
doe's anyone has this error with ios?

**Comment by 242617** [comment]
I have the same error. IOS, Go 1.9.

**Comment by mikehawkes** [comment]
This is still an issue on iOS when using an embedded layout. I now get past this by showing the window before adding widgets / layouts. With a single grid layout, I never get the problem when initially populating it; add a sub-layout and a few widgets and it fails without show()ing early in the build. However, I don't seem to be able to fix it occurring when I change orientation - I have, for the time being, locked orientation in Xcode to prevent the app crashing. So it looks like there's definitely something odd in the layout handlers.

**Comment by therecipe** [comment]
@mikehawkes yeah, sorry I looked into this 2 weeks ago when I worked on https://github.com/therecipe/qt/commit/4cdafbc0fd4438b50c3e48422cfb0e1c7567a9f4

It's basically the same issue as this one https://github.com/therecipe/qt/issues/399
I will need to investigate further if this is something I can fix or whether it's a general cgo issue

**Comment by mikehawkes** [comment]
More on this - Literally, I just open the app and rotate the iPhone and the app crashes. I've tried all sorts to allow me to change orientation - the only thing that seems to work is to hit the home button, change the orientation, and then reopen the app. The orientation change works and the app works normally. Is there any chance you could look at this at some point please? I'm having to lock orientation in Xcode at the moment. iPad and iPhone both do the same thing.

Sorry to band on about this one but it's driving me nuts. Happy to consider any workaround at this point too.

Thanks lots.

--

2019-03-27 17:14:58.402769+0000 main[927:26270] Metal GPU Frame Capture Enabled
2019-03-27 17:14:58.403396+0000 main[927:26270] Metal API Validation Enabled
Cache running - evicted: cacheInit, true
fatal: morestack on g0


main`___lldb_unnamed_symbol1017$$main:
    0x102445e98 <+0>:  mov    x0, #0x0
->  0x102445e9c <+4>:  ldr    x0, [x0] = Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)
    0x102445ea0 <+8>:  .long  0xbea71700                ; unknown opcode
    0x102445ea4 <+12>: .long  0x00000000                ; unknown opcode

**Comment by therecipe** [comment]
Okay, I looked into this again and it is probably a Go issue.

However, I was able to work around it for now by blacklisting a few functions with https://github.com/therecipe/qt/commit/fafeae32212b7961c6eb9b229468a7a97d650221#diff-9bbdf1b6f8e66f0a346330f3be71a4d3

Please let me know if you can rotate your app now :)

Also this example should work now
```go
package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	w := widgets.NewQWidget(nil, 0)
	wL := widgets.NewQVBoxLayout2(w)
	for i := 0; i < 25; i++ {
		l := widgets.NewQHBoxLayout()
		for j := 0; j < 10; j++ {
			l.AddWidget(widgets.NewQLabel2(fmt.Sprint(i, ":", j), w, 0), 0, 0)
		}
		wL.AddLayout(l, 0)
	}
	w.Show()
	widgets.QApplication_Exec()
}
```

**Comment by mikehawkes** [comment]
Nope, sorry - it's still failing. This is the window that causes the issue (I have a similar one for showing the output from a filter - both fail in the same way). 

It is a little better in that the main window (mainly pushbuttons) works nicely now. But anything with a QTextEdit or QPlainTextEdit fall over.

Code snippet below:

```// DisplayLogWindow displays the existing, or creates a new log window.
func (JS *JSQuery) DisplayLogWindow(JSWindow *widgets.QMainWindow) {
	if LW == nil || JS.LogWindow == nil {
		JS.LogWindow = widgets.NewQMainWindow(JSWindow, core.Qt__Window)
		JS.LogWindow.SetWindowTitle("Engine Log")
		JS.LogWindow.SetGeometry2(700, 0, 600, 800)
		JS.LogCW = widgets.NewQWidget(JS.LogWindow, core.Qt__Widget)
		JS.LogWindow.SetCentralWidget(JS.LogCW)

		// Use a rich-text edit widget to display the log.
		JS.LogOutput = widgets.NewQTextEdit2("", nil)
		JS.LogOutput.SetStyleSheet("QTextEdit {background:'black'; color:'#d0ffd0';}")
		JS.LogOutput.SetTabStopWidth(120)

		// Pushbutton to hide the log.
		JS.LogHide = widgets.NewQPushButton2("Hide", nil)
		JS.LogHide.SetIcon(JS.LogHide.Style().StandardIcon(widgets.QStyle__SP_DialogCancelButton, nil, nil))
		JS.LogHide.SetIconSize(core.NewQSize2(30, 30))
		JS.LogHide.SetSizePolicy2(1, 1)
		JS.LogHide.SetFlat(true)

		// Pushbutton to clear the contents.
		JS.LogClear = widgets.NewQPushButton2("Clear", nil)
		JS.LogClear.SetIcon(JS.LogClear.Style().StandardIcon(widgets.QStyle__SP_DialogApplyButton, nil, nil))
		JS.LogClear.SetIconSize(core.NewQSize2(30, 30))
		JS.LogClear.SetSizePolicy2(1, 1)
		JS.LogClear.SetFlat(true)

		// Action on hitting the 'hide' button.
		JS.LogHide.ConnectClicked(func(bool) {
			JS.LogWindow.Hide()
		})

		// Action on hitting the 'clear' button.
		JS.LogClear.ConnectClicked(func(bool) {
			JS.LogLines = &[]string{}
			JS.LogOutput.SetPlainText("")
		})

		// Layout the window,
		JS.LogLayout = widgets.NewQGridLayout2()
		JS.LogCW.SetLayout(JS.LogLayout)

		JS.LogLayout.AddWidget3(JS.LogOutput, 0, 0, 1, 2, 0)
		JS.LogLayout.AddWidget3(JS.LogHide, 1, 0, 1, 1, 0)
		JS.LogLayout.AddWidget3(JS.LogClear, 1, 1, 1, 1, 0)

		JS.LogLines = &[]string{}

		LW = JS
	}

	LW.LogWindow.Show()
}

**Comment by therecipe** [comment]
Mh, I looked into this more deeply yesterday but hit a dead end.
However, there is one last thing I can try.
I will let you know how it goes.

**Comment by therecipe** [comment]
Okay, I looked more extensive into this and blacklisted and tested a lot.
And finally came to the conclusion that it's a Go or Qt issue and I can't do much about it, furthermore I needed to enable `QtRunLoopIntegrationDisableSeparateStack` to get the binding working on iOS, and thereby changed Qt's default stack size behaviour.
So it might as well be a corner case issue only possible in this specific scenario, or maybe the stacksize is really to small. More info about `QtRunLoopInte...` [here](https://github.com/qt/qtbase/blob/5.12.3/src/plugins/platforms/ios/qioseventdispatcher.mm#L221)
And sadly I don't know enought about the inner workings of Qt nor Go to dig any deeper.
However, what I figured was that it's related to the deep somewhat recursive and sibling calling function calls made by Layouts (especially those found inside List/Table/TreeViews, but not limited to them).



On the bright side, I think I found a way to trivially work around this issue.
And in hindsight I should have thought about this a whole lot earlier.

The workaround is the following:

```go
gui.QGuiApplication_Screens()[0].SetOrientationUpdateMask(core.Qt__PrimaryOrientation | core.Qt__LandscapeOrientation | core.Qt__PortraitOrientation | core.Qt__InvertedLandscapeOrientation | core.Qt__InvertedPortraitOrientation)
gui.QGuiApplication_Screens()[0].ConnectOrientationChanged(func(core.Qt__ScreenOrientation) {
	mainWindow.Hide()
	go mainWindow.Show()
})
```

What this does, is to first enable the notification of screen orientation changes.
An second, intercept these notifications on the main thread, then immediately hide the mainwindow and queue up the show signal at the end of the main event loop.

This works, because the show function is a slot, and slots called from a different thread than the main thread are currently automatically scheduled to run on the main thread at some point later, once it's sufficient empty. Also first hidding the main window, removes the need to make these fatal recursive calls causing the crash.

This trick did at least work for the [common/widgets_demo](https://github.com/therecipe/qt/tree/master/internal/examples/common/widgets_demo) example, and is the best I can offer at this point.

Also this might still crash if you rotate your screen multiple times in a small time frame.
But you can probably make it more robust by using some mutex or something.
