### ISSUE TITLE
Compiling from OSX for Windows 10 64 bit

### ISSUE THREAD

**Issue by amlwwalker** [therecipe/qt#768]
Hi,
I have successfully compiled and run the application for OSX on OSX, and compilation seems fine for Windows 10 64bit in either shared mode or static mode.
However when I run it on windows, 64 bit gives me a flash of a qt window (no elements) then crashes. 
When I run the shared version I get a missing file issue:
![image](https://user-images.githubusercontent.com/2920180/51203496-26e55d80-18f9-11e9-91c3-c250ed34c359.png)

Is there a way I can debug the compiled exe? I tried running it from the command prompt but I get no output.
I think the static version will be just some qml/qt issue, but I can't know what it is without the debugging turned on. For the shared version, its a dll requirement, so I think thats going to be a bigger issue.

**Comment by therecipe** [comment]
Hey

Do you use an VM to test the QML application on windows?
If yes, then maybe take a look here https://github.com/therecipe/qt/issues/720#issuecomment-430249268
Basically you will either need to compile the application on Windows while using the official pre-built version of Qt, or use the `windows_64_shared_wine` image. Another workaround would be to force software rendering for your QML application on these machines.

>Is there a way I can debug the compiled exe? I tried running it from the command prompt but I get no output.

You should be able to get some output if you set `QT_DEBUG_CONSOLE=true` before using qtdeploy, however I just figured that this won't work with the `windows_64_shared_wine` image because wine apparently can't handle underscores in env vars ... but I will workaround this somehow.

>For the shared version, its a dll requirement, so I think thats going to be a bigger issue.

Maybe these changes https://github.com/therecipe/qt/commit/94a0fe87cf38a584bca5485e38379b0d8435775f fix it, I haven't tested it though
Just wait for new the images to be build and try again. It should take like 1-2 hours for them to be ready I think https://hub.docker.com/r/therecipe/qt/tags

**Comment by therecipe** [comment]
>When I open it on windows (yes its a VM - Virtual Box) It flashes up a small window and then it disappears (the content of loader-production.qml doesn't appear)

Yeah, then its probably the issue I wrote about here https://github.com/therecipe/qt/issues/720#issuecomment-430249268

Try using `quick.QQuickWindow_SetSceneGraphBackend(quick.QSGRendererInterface__Software)` before `widgets.NewQApplication`, this should somewhat make the application work on VirtualBox VMs.
Also the application should properly work on Parallels or VMWare VMs IIRC, it's just VirtualBox that causes trouble.

The widgets example is working fine, since it doesn't use OpenGL and therefor has no problems working on VirtualBox VMs.

>P.S - Are you saying the wine image will work on a windows VM and that compiling with static will work fine on an actual Windows machine, just not in the VM?

Yeah, also the static builds might work on other VMs just not on VirtualBox (but I haven't tested in a while).

**Comment by amlwwalker** [comment]
> Yeah, then its probably the issue I wrote about here #720 (comment)

Are those the images you mention you were building above, i.e you think in the latest image it will work in VMs?  I.e I can see `windows_64_static` was updated 1 hour ago

**Comment by therecipe** [comment]
No sorry, these images still won't work properly they will just fix the libssl issue for the `windows_*_shared` images.

But like I said, maybe try the `QQuickWindow_SetSceneGraphBackend` function and see if the static version shows something.

**Comment by amlwwalker** [comment]
Yeah I tried those. I get a small white empty window even on not-virtual windows. Current suspicion is its to do with the path to the qml file in main.go

**Comment by amlwwalker** [comment]
Hey, 
So I have tried with wine, and on an actual windows machine, static and shared, and within a VM. I get a flash of a window and thats it. Everything is working perfectly on mac, but without being able to get any debug information I am struggling to pin the issue down...
I have pushed my code to here, https://github.com/amlwwalker/pdf-editor
compling with `qtdeploy test desktop` from within the qt directory builds the application fine on mac.
I was wondering if you may be able to have a look and see if you can spot anything that would mean that this wouldn't work on windows.
It's odd because when I was working with therecipe/qt back in february last year, I was having no problems cross compiling for windows (even within a VM).
Any tips/help greatly appreciated.

Thanks

**Comment by therecipe** [comment]
I looked into this, and there are a few separate issues making it difficult to get this working on windows VirtualBox VMs at the moment ... Your code it fine though, beside one minor issue.

First to get it working you will need to apply this patch

```patch
diff --git a/qt/main.go b/qt/main.go
index a1c3c01..f3e29d0 100644
--- a/qt/main.go
+++ b/qt/main.go
@@ -34,6 +34,10 @@ func LoadConfiguration() (error, Config) {
 }
 func main() {
 
+	core.QCoreApplication_SetOrganizationName("OrganizationName") //needed to fix an QML Settings issue on windows
+
+	quick.QQuickWindow_SetSceneGraphBackend(quick.QSGRendererInterface__Software) //needed to get the application working on VMs when using the windows docker images
+
 	//0. set any required env vars for qt
 	// os.Setenv("QT_QUICK_CONTROLS_STYLE", "material") //set style to material
 	os.Setenv("QML_DISABLE_DISK_CACHE", "true") //disable caching files

```

The first change is for this issue https://bugreports.qt.io/browse/QTBUG-71669 which probably only affects windows 

The second change is to work around https://github.com/therecipe/qt/issues/720#issuecomment-430249268

These changes + the new docker image with these changes https://github.com/therecipe/qt/commit/e3109c215da173a767c4dbd2761a1320b78f7cdd should make 
`QT_DEBUG_CONSOLE=true qtdeploy -docker build windows_64_shared` work

But `QT_DEBUG_CONSOLE=true qtdeploy -docker build windows_64_shared` will still not work because it's missing the QtQuick.Controls module somehow (I will look into this)

---

Now to get `QT_DEBUG_CONSOLE=true qtdeploy -docker build windows_64_shared_wine` or normal windows deployments on windows hosts working you can remove the `quick.QQuickWindow_SetSceneGraphBackend` line from the patch above and build your application as usual

Then to solve this issue https://bugreports.qt.io/browse/QTBUG-71510 you will need to download this file https://download.qt.io/development_releases/prebuilt/d3dcompiler/msvc2010/D3DCompiler_43-x64.dll.7z and unzip it in next to your application.exe (You can then delete the other `D3DCompiler_47.dll` if you want)

Btw, if you build with `QT_DEBUG_CONSOLE=true` then you will need to open the application through an already open CMD otherwise you won't be able to see the console log.

**Comment by amlwwalker** [comment]
So for now, I am not compiling with the wine images because they take signifcantly longer to compile than the standard windows ones.

> These changes + the new docker image with these changes e3109c2 should make
> QT_DEBUG_CONSOLE=true qtdeploy -docker build windows_64_shared work
> 
> But QT_DEBUG_CONSOLE=true qtdeploy -docker build windows_64_shared will still not work because it's missing the QtQuick.Controls module somehow (I will look into this)
> 

Is there a typo in the above, it seems to be contradictory? The commands seem the same?


So to make sure I understand, for VM:

Apply path:

```
+	core.QCoreApplication_SetOrganizationName("OrganizationName") //needed to fix an QML Settings issue on windows
+
+	quick.QQuickWindow_SetSceneGraphBackend(quick.QSGRendererInterface__Software) //needed to get the application working on VMs when using the windows docker images
+
```
Create executable with 
`qtdeploy -docker build windows_64_shared`
or
`qtdeploy -docker build windows_64_static`

Remove 
`quick.QQuickWindow_SetSceneGraphBackend`

when running on actual windows.

The bit about downloading the dll and replacing the one is only relevant for shared compilations?

I'll let you know how I get on
Thanks!

**Comment by therecipe** [comment]
>So for now, I am not compiling with the wine images because they take signifcantly longer to compile than the standard windows ones.

Yeah, sadly there is probably nothing I can do about that. (There is a minor chance but I haven't had time to look into it)

>Is there a typo in the above, it seems to be contradictory? The commands seem the same?

Sorry yeah, it's a typo the static image will still not work.


>So to make sure I understand ...

Sounds all good, but `The bit about downloading the dll and replacing the one is only relevant for shared compilations?` yes that's only relevant for the `windows_64_shared_wine` image or normal deployments on windows machines (which are 64 bit and shared too).
But **not** for the `windows_*_shared` images (these are completely different and will probably always require the `SetSceneGraphBackend` workaround)

**Comment by amlwwalker** [comment]
Ok, I'm pulling the latest `windows_64_shared` now, once its done I will try to build for windows VM and see if it works. I have both the lines in the code from the patch now.
I've never actually seen it work as shared so will be interested.
Just for clarity, I'm trying not to use the wine images, so will be referring to the windows_64_shared/static images going forward

**Comment by therecipe** [comment]
Okay, just one thing
Even though the application should work with the `windows_64_shared` image, it will probably not display everything correctly if you are unlucky due the `SetSceneGraphBackend` workaround.
Take a look here https://doc.qt.io/qt-5.12/qtquick-visualcanvas-adaptations-software.html, "Shader Effects" and other things won't be available.

**Comment by amlwwalker** [comment]
Ok so if I understand correctly:
If it builds and runs on OSX fine then:

* **VM** `windows_64_shared` + `quick.QQuickWindow_SetSceneGraphBackend(quick.QSGRendererInterface__Software)` = partial functionality
* **VM/WinHost/OSX** + `windows_64_shared_wine` + DLL-fix = full functionality
* **VM/WinHost** +`windows_64_static/_wine` = no functionality

Theres a few combinations, so just getting a bit lost as to what I should expect with what build 😂 Happy for anything right now as I haven't seen it work outside of OSX yet
?

**Comment by therecipe** [comment]
>Ok so if I understand correctly:
If it builds and runs on OSX fine then:

Yeah, it's a bit confusing but your summary looks good

>I was running it from a network drive, and it was failing, I just moved to the desktop and that shared version works. Sweet!

Yeah sorry, that's another annoyance, I totally forgot about this issue. (there is nothing I can do about that)  I just got used to copy everything onto the desktop first, before running it.

>I assume still this wont work in shared mode (just because its much tidier as a single app)

You probably meant "static" ? ^^ And yes, but I will look into it.

>So its running now, I have an issue with retrieving the file paths when i use a file dialog.
Is it safe in qml to be using / on windows in paths, for instance:

Could be that windows wants backslashes instead, but I just would try it. The chances are good that normal slashes work just fine.

**Comment by amlwwalker** [comment]
Ok yeah, so its working in shared mode, I'll keep checking to see how static is getting on.

Re the paths OSX/Windows I have added a logging box to my gui as not yet successfully getting logs on a console, 
![image](https://user-images.githubusercontent.com/2920180/51278797-74ce9400-19d3-11e9-85b1-0052e8bbdc70.png)

(Running on Windows)
In that image, the first line, "User chose directory" - thats coming from qml, and is logged when the fileDialog is closed on choosing a directory.
The next line is coming from the backend (Go code). It has stripped off the `file://` (because UNIX needs the `/` as its part of the path, I have left the third `/` in). It has however flipped all the slashes round to meet the OS, so I consider so far as succesful.
The error on the third line fails, and I guess its because of the leading slash.
Is there a way you have found (only assuming you may have because you have been testing this across OS's) to handle this properly? I googled around for "Go OS file:///" but to no avail...

**Comment by therecipe** [comment]
>Ok yeah, so its working in shared mode, I'll keep checking to see how static is getting on.

I looked into the static build issue and it turned out to be this bug: https://bugreports.qt.io/browse/QTBUG-71386

And https://github.com/therecipe/qt/commit/0eb397b4e816bce61dcd17040530bde233217615 should fix this now and make
`QT_DEBUG_CONSOLE=true qtdeploy -docker build windows_64_static` work as well

>The error on the third line fails, and I guess its because of the leading slash.
Is there a way you have found (only assuming you may have because you have been testing this across OS's) to handle this properly? I googled around for "Go OS file:///" but to no avail...

Maybe I don't understand, but basically you would just need to do
```go
path := "file:///C:/User/amlwwalker/Desktop"
path = strings.TrimPrefix(path, "file:///")
path = filepath.Clean(path)
```
There is no need for a leading backslash on windows, and you probably don't even need to use `filepath.Clean` to make it work on Win7 or Win10, I would guess.

On a side note, the backlash can be used on windows if you want to use an UNC path https://en.wikipedia.org/wiki/Path_(computing)#Uniform_Naming_Convention, but I don't know if Go or Qt support these at all.

**Comment by amlwwalker** [comment]
Thanks for this. So I'm about to try the new static image, quick question - realise not directly associated with therecipe, apologies....

I am using this library github.com/gen2brain/go-fitz for converting pdfs to images. It all works great on OSX but when I built with *shared* image it crashes because of this library. It's a segmentation fault which makes me think its to do with the underlying c library and the integration with cgo.

I was wondering, because I have cross compiled libraries before for windows that use C underneath if using the static build instead of the shared build should solve this (as the libraries aren't dynamically loaded...???)

**Comment by therecipe** [comment]
>I was wondering, because I have cross compiled libraries before for windows that use C underneath if using the static build instead of the shared build should solve this (as the libraries aren't dynamically loaded...???)

I'm not sure it probably doesn't make a difference since it looks like `fitz` is always statically linked into your application. But I could be wrong, so it's worth a try.
(Maybe also try the "normal" deployment on windows, and/or the `wine` image since it could be that the other `windows_*` images are somewhat incompatible with `fitz` for some reason)

Also, if you create some small example I will try to look into it.

**Comment by amlwwalker** [comment]
Thanks alot for this.
Yeah so I built it with the static image and it still crashed on the when using that pdf library on windows. Reading around its perhaps to do with if cgo is enabled or not. I thought I had enabled it, but perhaps not.
I compiled it on Windows (VM) and still couldn't work the error out. I've made a small demo using fritz and therecipe/qt together [here](https://github.com/amlwwalker/fitz-qt)
To keep this post short, instructions are in the readme. In essence it allows you to edit pdf pages and save them as images. Any ideas, would be really helpful, thanks

**Comment by therecipe** [comment]
No, problem

I was able to reproduce it on windows and can also verify that it works on macOS.
It seems like `go-fitz` is broken on windows.
If you run `go test -v github.com/gen2brain/go-fitz` on macOS, it will pass but on windows it will fail with something like: 
```
=== RUN   TestImage
exit status 3221225477
FAIL    github.com/gen2brain/go-fitz    0.210s
```

You can simply reproduce it on windows by running
`%GOPATH%/bin/qtenv && go test -v github.com/gen2brain/go-fitz`
or by downloading and adding [gcc](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/6.4.0/threads-posix/seh/) to your path and then running
`go test -v github.com/gen2brain/go-fitz`

I did also test it with [gcc 7.3.0](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/7.3.0/threads-posix/seh/) and it failed as well, so you will probably have to open an issue on `go-fitz` about this

**Comment by amlwwalker** [comment]
Ok thanks for this, thats really annoying, I'll see if I can get a response from the author. In the meantime I will see if I can get imagemagick working on Windows, because even though I can get it working on mac, I don't think I will be able to cross compile it for Windows? Have you used therecipe/qt with imagemagick at all? The issue is I don't know how to compile the ghostscript into the build so that the cross compilation works

**Comment by amlwwalker** [comment]
Hey, so I have got hold of the original author of fitz which is interesting, he said he may get a chance to look but cant promise anything.
I've been looking at image magick as an alternative again, and I've got a simple imagemagick program proving that its working

```
package main

import (
	"fmt"
	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()
	mw := imagick.NewMagickWand()
	defer mw.Destroy()
	mw.SetResolution(300, 300)
	mw.SetIteratorIndex(0) // This being the page offset
	mw.SetCompressionQuality(100)
	mw.SetImageFormat("png")
	img := mw.ReadImage("XXXX.pdf")
	fmt.Println(img)
	mw.WriteImage("ftw.png")
}
```

That works fine, converting the pages of the PDF to png.
When I build with `qtdeploy test desktop` (I'm on mac now, as Im in the same place on both, so if I get it working on OSX, hoping I will understand how to get it working on windows) I get the following error

> Error reading pages  ERROR_MISSING_DELEGATE: no decode delegate for this image format `PDF' @ error/constitute.c/ReadImage/556

This is an imagemagick error stating that it doesn't know how to delegate the task off to ghostscript which handles rendering the pdf.

Installing imagemagick and ghostscript can be done with brew

`brew install ghostscript; brew install imagemagick`

So something about building with `qtdeploy` means that this no longer works. I dont quite understand what qtdeploy is doing, but my guess is that I need to statically build rather than dynamically but I'm not sure how you do that the 'normal' way (i.e without docker containers).

I have pushed to a branch in the same repository as before however now using imagemagick rather than fitz. The demo code above works fine after doing the brew install, but the imagemagick error appears when compiled with `therecipe/qt`
Probably the important line is https://github.com/amlwwalker/fitz-qt/blob/imagemagick/qt/pdf-management.go#L27 where the file is read

**Comment by therecipe** [comment]
I looked into this, but there is not much I can do about this.

The problem is that imagemagick has some dynamic dependencies (ghostscript, and also stuff it needs on its own) that are not properly deployed when using `qtdeploy`.

If you take a look at the content of your created `*.app` on macOS, you will see that the `Contents/Frameworks` folder contains something similar to the following:

```go
Frameworks
├── QtCore.framework
├── QtDBus.framework
├── QtGui.framework
├── QtPrintSupport.framework
├── QtSvg.framework
├── QtWidgets.framework
├── libMagickCore-7.Q16HDRI.6.dylib
├── libMagickWand-7.Q16HDRI.6.dylib
├── libfreetype.6.dylib
├── liblcms2.2.dylib
├── libltdl.7.dylib
├── liblzma.5.dylib
├── libomp.dylib
└── libpng16.16.dylib
```

The problem is now, that since `qtdeploy` and `macdeployqt` (the program that `qtdeploy` wraps internally) are not really meant to deploy 3rd party dependencies, the jobs is only half done and so there might be some libraries missing which leads to `Error reading pages ERROR_MISSING_DELEGATE`

Now to solve this, you would need to manually figure out which libs are missing and copy them inside the Frameworks dir or remove the following libs
```
├── libMagickCore-7.Q16HDRI.6.dylib
├── libMagickWand-7.Q16HDRI.6.dylib
├── libfreetype.6.dylib
├── liblcms2.2.dylib
├── libltdl.7.dylib
├── liblzma.5.dylib
├── libomp.dylib
└── libpng16.16.dylib
```
from the Framework dir and let the application use the home-brew libs.

You can also just run `rm -r deploy && qtdeploy -fast` during developing.

However, I would just try to get `go-fitz` working, since it's going to be statically linked into your application and therefore should save you a lot of trouble. Or you could try to statically link ghostscript and imagemagick, but that's probably going to be a lot of work.

Or the third option, tell your users to install ghostscript and imagemagick before running your application. (But you will need to remove all the "half" deployed imagemagick libs from the `*.app` before distributing your application)

**Comment by amlwwalker** [comment]
Yes I emailed the author of go-fitz but I also ran it with gdb to see what the output there looks like, and I get this:
![image](https://user-images.githubusercontent.com/2920180/51559400-adf68080-1e79-11e9-826b-0abb1a7213c6.png)

I know that this isn't your code, I just wondered if that "told" you anything that it doesn't tell me.....?

**Comment by therecipe** [comment]
>I know that this isn't your code, I just wondered if that "told" you anything that it doesn't tell me.....?

No, sorry probably not.

If the mingw-w64-crt hasn't changed, then the error is caused by https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-crt/stdio/fseeko64.c#L145, but I have no idea why this would break. Maybe try another pdf or use some absolute or relative path to your pdf, it could be that the pdf really isn't found or something.

>When I run rm -r deploy;qtdeploy -fast I get

To solve this you will probably need to run `$(go env GOPATH)/bin/qtsetup` first

>On OSX is there a shell/batch script that runs when the app starts? I was thinking, if it gets to this, of checking for imagemagick and ghostscript and if not installing them, before running the program.

You can change the executable that is started when opening the `*.app`, by editing the Info.plist (`CFBundleExecutable`)

>Incidently, can you recommend an installer creator for windows as the shared app is quite a lot of files to share with others, not very tidy as it comes

There are a few and it's quite a while since I worked with them, but any of those should do the job

https://docs.microsoft.com/en-us/windows/application-management/msix-app-packaging-tool
http://www.jrsoftware.org/isinfo.php
http://wixtoolset.org (also used by the Go Team to package Go [itself](https://github.com/golang/build/blob/master/cmd/release/releaselet.go#L224))

**Comment by amlwwalker** [comment]
Just to say the author of fitz responded and fixed the library on Windows. All is great now and all working. Can close this issue, but last question - can you compile statically the need for docker if its for the local environment - i.e not cross compiling?

**Comment by therecipe** [comment]
Yeah, you could use msys2 to statically compile on windows.
https://github.com/therecipe/qt/wiki/Installation-on-Windows#msys2-version-without-android-support

The "official" prebuilt version is always dynamically linked though.
