### ISSUE TITLE
qtmoc generates imports with conflicting names

### ISSUE THREAD

**Issue by ziflex** [therecipe/qt#988]
Hey,

I've noticed that when ``qtmoc`` generates imports it does not resolve names collisions of imported modules. 
Plus, it's kind of magic to me how it decides what to import, because it generates some module imports that aren't really used in generated files. I have to remove the import.

**Comment by therecipe** [comment]
Hey

Yeah, qtmoc is having problems with name collisions and I wrote a bit about it here https://github.com/therecipe/qt/issues/975#issuecomment-540742069 recently as well.
But the truth is, that I fucked up when creating qtmoc in the beginning and now I will have to rewrite some core mechanic to get namespaces working for qtmoc, and also to properly support the `3d` Qt module.
I hope that I can fix this in the next few months, but making the changes will be quit time consuming and so I can't really give an estimate.

However there is a small chance that your issue was resolved with the recent changes made with https://github.com/therecipe/qt/commit/3904ec6ceb7b0f2e042c85450c8ca123a1396fb9, could you maybe test the current master or this commit?

Also could you maybe provide some small example code so I can reproduce the issue?

**Comment by ziflex** [comment]
I see.
I'm afraid I reinstall everything just yesterday and it's still failing.

It's not a deal breaker for me, I can manually remove it, but I guess I will have to commit the generated files in order to make CI/CD work properly.

**Comment by ziflex** [comment]
The odd thing about this is that it imports a module that is not required at all.
Among of my app dependencies is this module ``"github.com/mafredri/cdp/protocol/runtime"`` which gets imported by mistake.
I guess the tool looks up for ``runtime`` module and brings in it by mistake.

**Comment by therecipe** [comment]
Ahh its about name collisions of module imports, sorry it seems like I misread your initial report.
I looked into it now and made some changes with https://github.com/therecipe/qt/commit/1097424d656c23c9c8372222a6d8f2a7bcef0fa2 which should hopefully fix this.

What I wrote about earlier, are name collision of "moc structs".
You can work around those issues by slightly re-naming the troubling structs though.

**Comment by ziflex** [comment]
Awesome, the fix works!
